import Head from "next/head";
import Topo from '@/componentes/topo/';
import Banner from '@/componentes/secaoCapa/';
import Produtos from '@/componentes/secaoProdutos/produtos';
import SobreNos from "@/componentes/sobreNos";
import Footer from '@/componentes/footer'





export default function Home() {
  return (
    <>
      <Head>
        <title>Otica Vida</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
     <main>
      <Topo/>
      <Banner/>
      <Produtos/>
      <SobreNos/>
      <Footer/>
     </main>
    </>
  );
}
